[project]
name = "synthetic-healthlake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.4.2",
    "ruff>=0.14.7",
]
