version: 0.1
domains:
  patient:
    constraints:
      - id: "patient_age_range"
        type: "range"
        applies_to:
          model: "omop.person"
          field: "year_of_birth"
        params:
          min_year: 1920
          max_year: 2020
